### ISSUE TITLE
[Version Update] Update mod to 1.21.3

### ISSUE THREAD

**Issue by SmokyTheCat** [Crec0/map-in-slot#10]
Map In Slot 3.1.2 works in 1.21 and 1.21.1 but the game crashes in 1.21.3

**Comment by Crec0** [comment]
Looking into this

**Comment by SmokyTheCat** [comment]
It's been working good, haven't ran into any issues, it also works in 1.21.4. Could you update the Modrinth page to include 1.21.4?

**Comment by Crec0** [comment]
Added
